### ISSUE TITLE
2FA dla aplikacji sin-net-reports

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#174]
Dodanie do aplikacji dwuskładnikowego uwierzytelniania, pola secret key i kod zabezpieczający (pole tekstowe).
pole w przyszłości będzie widoczne dla prtal świadczeniodawcy, SZOI i portal personelu. Należy pamiętać że jeden Klient może mieć dostęp do kilku oddziałów NFZ a dla każdego oddziału będzie inny sekretny klucz.

**Comment by siudeks** [comment]
@sinnetradek potwierdź czy 2fa działa jak powinno. Pomiń problem z zapisem czasu ostatniej aktualizacji, który został zgłoszony przez @robalbator jako odrębne issue #177
