### ISSUE TITLE
zmiany w zakładce klienci dział autoryzacje

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#41]
1. po wybraniu typu autoryzacji np. portal świadczeniodawcy w polach gdzie jest wpis nr klienta zmiana na kod świadczeniodawcy
2. dla działu portal personelu dodać pole odział NFZ, kod personelu pole użytkownik i hasło zostaje bez zmian
3. dla działu MUS dodać pole odział NFZ, kod świadczeniodawcy pole użytkownik i hasło zostaje bez zmian
4. dla działu Ewuś dodać pole odział NFZ, kod świadczeniodawcy pole użytkownik i hasło zostaje bez zmian

**Comment by siudeks** [comment]
Zrobione
