### ISSUE TITLE
dodanie wyświetlania danych podczas wpisywania usługi

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#42]
po wybraniu usługa - nowa usługa pomiędzy polem pracownik a klient jest pusta przestrzeń fajnie by było jak by po wybraniu klienta pokazywały by się tam dane z bazy klienci 

1. operator
2. dystans
3. pełen adres bo Medarów mamy bez liku a przy wyborze klienta nie widać adresu my juz w nazwie piszemy czy to medar Łęczyca, czy Pabianice
4. i już po nowemu kod świadczeniodawcy brany z Portal świadczeniodawcy lub z SZOI nr pierwotny umowy na to będę zaraz robił zgłoszenie na numer pierwotny

**Comment by siudeks** [comment]
Wszystkie zmiany wprowadzono oprócz zarysowanego tylko pomysłu na *nr pierwotny umowy*, który trezba będzie dopiero opisać następnym zgłoszeniem
