### ISSUE TITLE
raport miesięczny

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#43]
1. [x] brak nagłówka z danymi klienta nazwa, adres tak jak było w poprzednim
2. [x] w polu serwisant zamiast przedrostka adresu email (loginu) na wydruku poproszę imię i nazwisko powiązane z mailem
3. [x] Raport podzielimy na 2 części usługi z czasem podsumowane i w 2 części usługi z czasem 0:00 (tu mogą być kilometry sumowane)
4. [x] Wszystkie usługi zawierające czas 0:00  poproszę o fajną kreskę na raporcie i wyświetlenie ich w 2 części raportu
5. [x] dalej nie podoba mi się czcionka na raporcie jakiś Arial poproszę, Tahoma coś takiego ładnego
6. [x] podsumowanie na raporcie czy ostatnia linijka musi być w ramce ładnie by wyglądało podsumowanie bez ramki i pogrubiona czcionka

**Comment by siudeks** [comment]
Font: OpenSans

**Comment by siudeks** [comment]
Możliwe dodanie w bazie danych pełnej nazwy dla serwisanta, będzie wyświetlana na raporcie.

**Comment by siudeks** [comment]
Nagłówek jest, poprosiłem o dospecyfikowanie czego brakuje

**Comment by siudeks** [comment]
Pozycje bez czasu są w odrębnej, drugiej sekcji raportu

**Comment by siudeks** [comment]
Pogrubienie bezramkowe dodane w stopce
