### ISSUE TITLE
test 29-07-2021

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#44]
wszystko działa

**Comment by siudeks** [comment]
W bibliotece której użyłem nie ma funkcjonalności podpowiadania po treści tekstu. Na tą chwilę możemy albo A) wejść jak jest i pracować na tym później B) nie wchodzić w nową aplikację jeszcze do czasu aż wymyślę jak zrobić *jakiś* autocomplete.

Na razie włączyłem wprowadzanie bardziej swobodnego tekstu w oknie wyboru klienta, co nie jest rozwiązaniem ale będzie dla użytkowników elastyczniejsze
