### ISSUE TITLE
Ograniczenie przewijania strony wyłącznie do wpisów serwisowych

### ISSUE THREAD

**Issue by robalbator** [onlexnet/sin-net-reports#50]
taka propozycja estetyczno-ergonomiczna
jakby stronę podzielić na sekcje, tj kolumna po lewo (1)

![image](https://user-images.githubusercontent.com/92522179/140306135-c58ae1c3-2ae2-47eb-886c-85710b0f8703.png)

i  od góry wiersz (2), gdzie stałe elementy by się nie przewijały razem ze stroną, to samo z edycją klienta, jakby u góry zostawał pasek z przyciskami (3)
![image](https://user-images.githubusercontent.com/92522179/140306583-0237a690-e986-4bc6-99a5-f5608b2887a4.png)

**Comment by siudeks** [comment]
@robalbator wdrożone, jak zawsze przyjmuję reklamacje

**Comment by robalbator** [comment]
super, dziękuję podoba mnie się :)

jeszcze tylko jakby tak samo jak w usługach działało przy edycji danych 
klienta było by jeszcze superniej

*Pozdrawiam*
	
Robert Batorski

*SIN.NET - Systemy Komputerowe*
t: 	42 681 62 94 k: +48 725 875 757 <tel:48725875757>
a: 	Ossendowskiego 4, 93-228 Łódź
w: 	www.sin.net.pl <http://www.sin.net.pl> e: ***@***.***

W dniu 22.11.2021 o 23:56, Sławomir Siudek pisze:

**Comment by siudeks** [comment]
Zakładaj ticket :)

wt., 23 lis 2021, 08:45 użytkownik robalbator ***@***.***>
napisał:
