### ISSUE TITLE
wyszukiwanie klientów przy dodawaniu usług

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#58]
Przy dodawaniu usług w polu wybór klienta działa wyszukiwanie w locie tylko po nazwie klienta, proszę o dodanie wyszukiwania również po kodzie świadczeniodawcy (portal świadczeniodawcy/kod świadczeniodawcy)

**Comment by siudeks** [comment]
![XUwNbeYxBd](https://user-images.githubusercontent.com/3256574/143307266-2b5f8805-2486-4429-ac72-ad13b2bce2fa.gif)

**Comment by siudeks** [comment]
@robalbator Ta funkcjonalność przestała działać ?

**Comment by robalbator** [comment]
Dokładnie ta funkcjonalność z tym że nie tylko w obszarze edycji danych klienta ale i w obszarze wyboru klienta podczas dodawania usługi

**Comment by siudeks** [comment]
Wrzucone na produkcję ALE tylko w zakresie wyszukiwania na liście klientów. Wyszukiwania w tej samej postaci przy dodawaniu nowej usługi nie było (nie pamiętam) - proszę o założenie nowego issue bo tam będzie trzeba trochę dopisać logiki.
@robalbator  Tutaj poproszę 1) zweryfikować czy działa na produkcji jak oczekiwane 2) zamknąć zgłoszenie jeżeli działa poprawnie - lub nie zamykać zgłoszenia i dopisać w nowym komentarzu co nie działa

**Comment by sinnetradek** [comment]
Potwierdzam, przy wyszukiwaniu klientów działa - zamykam zgłoszenie + dodaję nowe na wyszukiwanie po kodzie świadczeniodawcy przy dodawaniu usług
