### ISSUE TITLE
zła godzina po zmianie hasła w zakładce klienci 

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#59]
Po zmianie hasła u klienta widzimy, że jest zła godzina ustawiona (pewnie strefa czasowa)

**Comment by siudeks** [comment]
- [ ] Generate date/time as UTC value fro mserver
- [ ] Consume UTC on client side and format to *dd/MM/yyyy hh:mm*

**Comment by siudeks** [comment]
Zrobione i wrzucone na produkcję
![image](https://user-images.githubusercontent.com/3256574/142742332-9681341a-1a59-4c26-a73d-87bd9428a958.png)
