### ISSUE TITLE
uwagi do raportu miesięcznego

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#60]
nie wiem czy to robiłeś więc dla porządku zgłaszam jeszcze raz
[9-ZDROWIE Sp. Z o.o..pdf](https://github.com/onlexnet/sin-net-reports/files/7574517/9-ZDROWIE.Sp.Z.o.o.pdf)

- [x] chciałbym poprosić czy dało by się żeby imię nazwisko mieściło się w 1 linijce najdłuższe jakie mamy to KAROLINA PAGACZ-DUDKIEWICZ / może skrócimy do imienia ale mam y 2 Anny (może być mniejsza czcionka)
- [x] pozycja nr 2 tam gdzie się drukują usługi z czasem 00:00 chciałbym by ten czas był widoczny 00:00  kilometry zostają (czyli dodać kolumnę czas) na posumowaniu tez poproszę 00;00
- [x] i przed pozycją nr 2 poproszę nagłówek USŁUGI DODATKOWE
- [x] Datę (dzień) i praca wykonana poproszę o wyśrodkowanie  reszta bez zmian
- [x] nazwę dane Klienta poproszę o pogrubienie

**Comment by siudeks** [comment]
@sinnetradek dostępne na Beta
