### ISSUE TITLE
prośba o raport zestawienie godzin pracownicy i podział klientów

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#61]
brakuje 2 raportów aport zestawienie godzin pracownicy i podział klientów

**Comment by siudeks** [comment]
@sinnetradek  pytania
1. czy w raporcie godzin dla pracownika chcesz też podsumowanie kilometrów?

**Comment by sinnetradek** [comment]
Cześć, tak poproszę_ /_ /_ / Wysłano z telefonu_ / _ / _ /  Z poważaniem_ /_ /_ / Radek Osiński
-------- Oryginalna wiadomość --------Od: Sławomir Siudek ***@***.***> Data: 02.12.2021  20:16  (GMT+01:00) Do: onlexnet/sin-net-reports ***@***.***> DW: sinnetradek ***@***.***>, Mention ***@***.***> Temat: Re: [onlexnet/sin-net-reports] prośba o raport zestawienie godzin pracownicy i podział klientów (Issue #61) 

@sinnetradek  pytania



czy w raporcie godzin dla pracownika chcesz też podsumowanie kilometrów?

**Comment by siudeks** [comment]
@sinnetradek  wszystkie raporty są już dostępne na beta, proszę o zielone światło wejścia na produkcję jak przetestujesz
