### ISSUE TITLE
Ograniczenie przewijania strony wyłącznie do wpisów serwisowych cd.

### ISSUE THREAD

**Issue by robalbator** [onlexnet/sin-net-reports#66]
Proszę o pochylenie się również nad drugą częścią prośby ;)

![image](https://user-images.githubusercontent.com/92522179/142989012-149ee881-09ff-4743-9f46-3e9bfeae667f.png)

**Comment by siudeks** [comment]
@robalbator to było poprzednio opisane? W takim razie moje niedopatrzenie. Myślałem że coś nowego mamy zmieniać. Popatrzę.

**Comment by siudeks** [comment]
@robalbator wrzucone. Jak nie widzisz zmian po wrzucaniu nowej wersji, to naciśnij ctrl + F5 aby wymusić odświeżenie
