### ISSUE TITLE
zmiany w klienci

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#71]
- [x] Dodać w KLIENCI dział autoryzacje logowanie RPWDL (rejestr podmiotów wyk. działalność leczniczą, tam gdzie jest do wyboru Portal świadczeniodawcy, DILO itd.) 
- [x] W klienci autoryzacje i dane kontaktowe poszerzyć pola do widoczności 40 znaków (nie widać adresów email i dłuższych wpisów)

**Comment by siudeks** [comment]
@sinnetradek  Zrobione. Na Beta. Brzydkie to teraz.
