### ISSUE TITLE
po zalogowaniu cały system raport

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#72]
- [x] Ustawić aby po zalogowaniu pokazywał domyślnie tylko moje usługi jak ktoś będzie chciał przełączy się na wszystkie (dostałem zgłoszenia że wygodniej się pracuje jak z automatu widać tylko moje usługi)
- [x] widok suma godzin czy może być wyraźniejszy jest taki wyszarzały mało widoczny
- [x] Wymuszenie przy wprowadzaniu usługi podania/wybrania klienta w chwili obecnej można wpisać usługę z czasem i km bez podania klienta tzw. pustą 
- [x] Czas automatycznego wylogowania po okresie bezczynności jaki jest ustawiony? ja zazwyczaj odpalam rano i mam cały czas na zakładce w przeglądarce raport żeby wpisywać na bieżąco. Nie sprawdzałem ale strasznie szybko raport się wylogowuje i trzeba się logować ponownie to wychodzi nawet kilkanaście razy w ciągu dnia pracy. Może ustawić półtorej godziny chyba że są jakieś względy bezpieczeństwa lub wydajności.

**Comment by siudeks** [comment]
@sinnetradek  zmieniłem długość na 12h, sprawdź czy będzie trzymało sesję

**Comment by siudeks** [comment]
Zmiany dostępne do testów na Beta
