### ISSUE TITLE
Raport miesięczny

### ISSUE THREAD

**Issue by sinnetradek** [onlexnet/sin-net-reports#73]
1. Jak zrobisz raport miesięczny to generują się pliki PDF ale dla 1 klienta generuje się katalog i dopiero w katalogu jest plik.
ten klient ma w nazwie znak / 
![obraz](https://user-images.githubusercontent.com/74017152/148697732-daa0c94a-c762-43d7-b617-ebea9b48f97a.png)

2. Proszę o dodanie w nazwach lików numeracji 3 znakowej 000; 001; 002 źle się sortują np w RobalCommander

**Comment by siudeks** [comment]
Zrobione, dostępne na beta
