### ISSUE TITLE
Login panel

### ISSUE THREAD

**Issue by robalbator** [onlexnet/sin-net-reports#88]
At logon apge it would be nice to change order of moving focus to: 1,2,3... currently is 1,4,2,3
![image](https://user-images.githubusercontent.com/92522179/150159396-392a523d-7b90-4d6a-b4b4-c25ca2c36328.png)

**Comment by siudeks** [comment]
Right now it is not doable, because login view is provided by Microsoft. I am closing the issue now, maybe will reopen in the future if I know how to customize such view
